- hosts: server
  vars:
    - image: devopsjaya2020/docker-ansible
  tasks:
    - name: install docker python ubuntu
      apt:
        name: "{{ item }} "
        state: present
      loop:
      - python
      - python-docker
      when:
      - ansible-distribution == "Ubuntu"
    - name: install && docker python centos
      yum: 
        name: python-docker
       state: present
      when:
      - ansible_distribution == "CentOS"
    - name: pull image docker
      docker_image:
        name: "{{ item }} "
        state: present
        force: yes
    - name: create container
      docker_container:
        name: container_docker_ansible
        state: started
        image: "{{ image }}"
        recreate: yes
        published_ports:
        - 8090:80
      
      
